### ISSUE TITLE
10: As a user I want to see the distance between the selected street & centre on the map with an indicator like a line.

### ISSUE THREAD

**Issue by jsjambar** [Wiejeben/HR-Project-3#11]
PRODUCT BACKLOG
 SPRINT 1 BACKLOG
 SPRINT 2 BACKLOG
 SPRINT 3 BACKLOG

Explore
- Calculate the distance between the current street and the center of the city
- Show the distance between the current street and the center of the city

**Comment by jeroen-meijer** [comment]
https://developers.google.com/maps/documentation/javascript/shapes !!!!!

**Comment by jeroen-meijer** [comment]
- legenda
